framework:
    messenger:
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                retry_strategy:
                    max_retries: 5
                    delay: 30000 # 30 seconds in milliseconds.
                    multiplier: 1 # Don't multiply delay before each retry.

        routing:
            App\Message\DownloadEpisodeMessage: async
            App\Message\ParseFeedMessage: async
            '*': async
