framework:
    messenger:
        transports:
            sync: 'sync://'
        routing:
            App\Message\DownloadEpisodeMessage: sync
            App\Message\ParseFeedMessage: sync
            '*': sync
